In [1]:
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
#import libraries
import requests
import pandas as pd
import time
from selenium.webdriver.support.wait import WebDriverWait
import selenium.webdriver.support.expected_conditions as ec
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

In [2]:
# Creation of a new instance of Google Chrome
browser = webdriver.Chrome(executable_path='/Users/johnnyhome/Downloads/chromedriver')

browser.get('https://www.linkedin.com/login')

/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/4204235804.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(executable_path='/Users/johnnyhome/Downloads/chromedriver')

In [3]:
# your secret credentials:
import getpass
email = "feteezuk@gmail.com"
password = getpass.getpass()

········

In [4]:
# Go to linkedin and login
time.sleep(3)
browser.find_element_by_id('username').send_keys(email)
browser.find_element_by_id('password').send_keys(password)
time.sleep(3)
browser.find_element_by_id('password').send_keys(Keys.RETURN)
#Set Sleep time of 20
time.sleep(3)

/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/3275404169.py:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_id('username').send_keys(email)
/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/3275404169.py:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_id('password').send_keys(password)
/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/3275404169.py:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_id('password').send_keys(Keys.RETURN)

In [6]:
#Type Recruiter into text box and hit enter

search_term = "Recruiter"

input = browser.find_element_by_class_name('search-global-typeahead__input')
input.send_keys('Recruiter')
time.sleep(3)
input.send_keys(Keys.RETURN)

/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/3453028063.py:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  input = browser.find_element_by_class_name('search-global-typeahead__input')

In [7]:
#CLICK ON PEOPLE to get list of people #
browser.find_element_by_xpath("/html/body/div[5]/div[3]/div/div[2]/section/div/nav/div/ul/li[1]/button").click()



#browser.find_element_by_class_name("search-reusables__filter-pill-button").send_keys(Keys.RETURN)

/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/2769079051.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_xpath("/html/body/div[5]/div[3]/div/div[2]/section/div/nav/div/ul/li[1]/button").click()

In [8]:
title=[]
name = []
number_of_connections=[]
link = []
iter=1
while iter<5:
    the_link="https://www.linkedin.com/search/results/people/?keywords=recruiter&origin=SWITCH_SEARCH_VERTICAL&page="
    the_link = the_link+str(iter).strip()
    browser.get(the_link)

    desc = browser.find_elements_by_class_name("entity-result__title-text")

    x=0
    #Get Name and NUMBER of connections
    while x < len(desc):
        name_and_deg_aray = desc[x].text.split("\n")
        name.append(name_and_deg_aray[0]) #Don't change 0, it grabs name and puts into array
        number_of_connections.append(name_and_deg_aray[3])
        link.append(browser.find_element_by_partial_link_text(name_and_deg_aray[0]).get_attribute("href"))
        x=x+1
    

    # Get JOB Title of reCruiter
    x=0
    title_aray = browser.find_elements_by_class_name('entity-result__primary-subtitle')
    while x < len(title_aray):
        title.append(title_aray[x].text)
        x=x+1
    
   
    iter=iter+1
    
#create DataFrame 
df=pd.DataFrame({'name': name,'title':title, 'number_of_connections':number_of_connections, 'link':link})




#df2 = df2.append(df)
#df2

/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/490349967.py:11: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  desc = browser.find_elements_by_class_name("entity-result__title-text")
/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/490349967.py:19: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  link.append(browser.find_element_by_partial_link_text(name_and_deg_aray[0]).get_attribute("href"))
/var/folders/8v/lrbknlbd3tlct98vvpqnqybr0000gn/T/ipykernel_6277/490349967.py:25: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  title_aray = browser.find_elements_by_class_name('entity-result__primary-subtitle')

In [9]:
df

,name,title,number_of_connections,link
0,Shakiba Sedighi,Tech Recruiter | Slack,2nd degree connection,https://www.linkedin.com/in/shakiba-sedighi-22...
1,Nathan Briggs,Recruiter,2nd degree connection,https://www.linkedin.com/in/nabriggs?miniProfi...
2,Christina Hwang,Technical Recruiter at Stripe,2nd degree connection,https://www.linkedin.com/in/christinashwang?mi...
3,Selam Desta,Technical Recruiter at Google,2nd degree connection,https://www.linkedin.com/in/selam-desta-aa32a5...
4,Tess Phan (Reddick),Recruiter at ON24,2nd degree connection,https://www.linkedin.com/in/tess-phan-reddick-...
5,Sherry H.,Executive Recruiter,2nd degree connection,https://www.linkedin.com/in/sherry-h-28295b1?m...
6,Sophie Bracewell,Recruiter at Airbnb,2nd degree connection,https://www.linkedin.com/in/sophiebracewell?mi...
7,Neelu Jain,Leadership Recruiter - Product,2nd degree connection,https://www.linkedin.com/in/neelujain?miniProf...
8,Greg Snyder,Tech Recruiter - Sendoso,2nd degree connection,https://www.linkedin.com/in/greg-snyder-346530...
9,Bella Kushnir,Recruiter at Meta,2nd degree connection,https://www.linkedin.com/in/bella-kushnir-8563...
10,Khin Phong,Recruiter at Robinhood,2nd degree connection,https://www.linkedin.com/in/khin-phong-165b461...
11,Gabrielle S.,Technical Talent Acquisition Specialist | Bloc...,2nd degree connection,https://www.linkedin.com/in/gabrielle-s-7a2785...
12,Joan Mendoza,Technical Recruiter @ Google,2nd degree connection,https://www.linkedin.com/in/joanmendoza?miniPr...
13,Jonathan Huie,Technical Recruiter at Airtable,2nd degree connection,https://www.linkedin.com/in/jonathan-huie?mini...
14,Bryce Anable,Senior Recruiter at Amplitude,2nd degree connection,https://www.linkedin.com/in/bryce-anable-9066a...
15,Aaron Geiman,Senior Technical Recruiter at StyleSeat,2nd degree connection,https://www.linkedin.com/in/aaron-geiman?miniP...
16,Mel Mussa,Talent Acquisition Recruiter at Charles Schwab,2nd degree connection,https://www.linkedin.com/in/mel-mussa-80a1b926...
17,Korina Lealiiee,Recruiter at Sendoso,2nd degree connection,https://www.linkedin.com/in/korina-lealiiee-78...
18,Danna Hughes,Software Engineering Recruiter at Google,2nd degree connection,https://www.linkedin.com/in/danna-hughes-4539a...
19,Katelyn Ewe,Technical Recruiter at Podium,2nd degree connection,https://www.linkedin.com/in/katelyn-ewe?miniPr...
20,Ryan Tong,Recruiter @ Fortinet,2nd degree connection,https://www.linkedin.com/in/ryantongs?miniProf...
21,"Jasmine Nouri, Esq.",Associate Recruiter at Salesforce,2nd degree connection,https://www.linkedin.com/in/jasmine-nouri-esq-...
22,Alan Alcantara,Technical Recruiter @ Linked[In],2nd degree connection,https://www.linkedin.com/in/alanalc04?miniProf...
23,Kristen Pawloski,Technical Recruiter at Pinterest 📌,2nd degree connection,https://www.linkedin.com/in/kjpawloski?miniPro...
24,Alyssa Cavalli,Senior Recruiter at TripActions,2nd degree connection,https://www.linkedin.com/in/alyssa-cavalli-1b4...
25,Meredith Alvin,Technical Recruiter at Stripe,2nd degree connection,https://www.linkedin.com/in/meredithalvin?mini...
26,Alvin Hui,Technical Recruiter at Plaid - I'm hiring!,2nd degree connection,https://www.linkedin.com/in/huialvin?miniProfi...
27,Monaaz Sarkari,Senior Talent Acquisition Recruiter,2nd degree connection,https://www.linkedin.com/in/monaazsarkari?mini...
28,Nikki (Winegred) Foreman,Technical Recruiter at LinkedIn,2nd degree connection,https://www.linkedin.com/in/nikki-winegred-for...
29,David Obad,Medical Device Recruiter at NCompass Recruiting,2nd degree connection,https://www.linkedin.com/in/davidobad?miniProf...
30,Christina Cartner,Senior Recruiter at Intercom | We're hiring!🚀,2nd degree connection,https://www.linkedin.com/in/christina-cartner-...
31,Alejandra Ceja,Senior Recruiter at Square,2nd degree connection,https://www.linkedin.com/in/alejandraceja?mini...
32,Lauren Novita,Senior Executive Recruiter at Coinbase,2nd degree connection,https://www.linkedin.com/in/lauren-novita-4551...
33,Gabrielle Leal,Recruiter at Meta,2nd degree connection,https://www.linkedin.com/in/gabrielleleal?mini...
34,Frank Sperry,Senior Technical Recruiter @ Nextdoor - We’re ...,2nd degree connection,https://www.linkedin.com/in/franksperry22?mini...
35,Maryann Hamed,Executive Recruiter at Heidrick & Struggles,2nd degree connection,https://www.linkedin.com/in/mafhamed?miniProfi...
36,Stephanie Kiraly,Technical Recruiter at Dropbox,2nd degree connection,https://www.linkedin.com/in/stephanie-kiraly-1...
37,Viviana Ramirez,Recruiter at Allbirds,2nd degree connection,https://www.linkedin.com/in/vivir?miniProfileU...
38,Sandy Dhami,Technical Recruiter at Autodesk,2nd degree connection,https://www.linkedin.com/in/sandydhami?miniPro...
39,Eugene Son,Senior Recruiter at Cruise,2nd degree connection,https://www.linkedin.com/in/eugeneson?miniProf...

In [10]:
len(df)

40

In [11]:
#Filter Recuiters that work for google
df[df['title'].str.contains("Google")]

,name,title,number_of_connections,link
3,Selam Desta,Technical Recruiter at Google,2nd degree connection,https://www.linkedin.com/in/selam-desta-aa32a5...
12,Joan Mendoza,Technical Recruiter @ Google,2nd degree connection,https://www.linkedin.com/in/joanmendoza?miniPr...
18,Danna Hughes,Software Engineering Recruiter at Google,2nd degree connection,https://www.linkedin.com/in/danna-hughes-4539a...

In [12]:
#Filter for Tech recuiters
df[df['title'].str.contains("Tech")]

,name,title,number_of_connections,link
0,Shakiba Sedighi,Tech Recruiter | Slack,2nd degree connection,https://www.linkedin.com/in/shakiba-sedighi-22...
2,Christina Hwang,Technical Recruiter at Stripe,2nd degree connection,https://www.linkedin.com/in/christinashwang?mi...
3,Selam Desta,Technical Recruiter at Google,2nd degree connection,https://www.linkedin.com/in/selam-desta-aa32a5...
8,Greg Snyder,Tech Recruiter - Sendoso,2nd degree connection,https://www.linkedin.com/in/greg-snyder-346530...
11,Gabrielle S.,Technical Talent Acquisition Specialist | Bloc...,2nd degree connection,https://www.linkedin.com/in/gabrielle-s-7a2785...
12,Joan Mendoza,Technical Recruiter @ Google,2nd degree connection,https://www.linkedin.com/in/joanmendoza?miniPr...
13,Jonathan Huie,Technical Recruiter at Airtable,2nd degree connection,https://www.linkedin.com/in/jonathan-huie?mini...
15,Aaron Geiman,Senior Technical Recruiter at StyleSeat,2nd degree connection,https://www.linkedin.com/in/aaron-geiman?miniP...
19,Katelyn Ewe,Technical Recruiter at Podium,2nd degree connection,https://www.linkedin.com/in/katelyn-ewe?miniPr...
22,Alan Alcantara,Technical Recruiter @ Linked[In],2nd degree connection,https://www.linkedin.com/in/alanalc04?miniProf...
23,Kristen Pawloski,Technical Recruiter at Pinterest 📌,2nd degree connection,https://www.linkedin.com/in/kjpawloski?miniPro...
25,Meredith Alvin,Technical Recruiter at Stripe,2nd degree connection,https://www.linkedin.com/in/meredithalvin?mini...
26,Alvin Hui,Technical Recruiter at Plaid - I'm hiring!,2nd degree connection,https://www.linkedin.com/in/huialvin?miniProfi...
28,Nikki (Winegred) Foreman,Technical Recruiter at LinkedIn,2nd degree connection,https://www.linkedin.com/in/nikki-winegred-for...
34,Frank Sperry,Senior Technical Recruiter @ Nextdoor - We’re ...,2nd degree connection,https://www.linkedin.com/in/franksperry22?mini...
36,Stephanie Kiraly,Technical Recruiter at Dropbox,2nd degree connection,https://www.linkedin.com/in/stephanie-kiraly-1...
38,Sandy Dhami,Technical Recruiter at Autodesk,2nd degree connection,https://www.linkedin.com/in/sandydhami?miniPro...

In [13]:
df[df['title'].str.contains("hiring")]

,name,title,number_of_connections,link
26,Alvin Hui,Technical Recruiter at Plaid - I'm hiring!,2nd degree connection,https://www.linkedin.com/in/huialvin?miniProfi...
30,Christina Cartner,Senior Recruiter at Intercom | We're hiring!🚀,2nd degree connection,https://www.linkedin.com/in/christina-cartner-...